/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./worker-configuration.d.ts` (hash: 9626927163d40062966ecd4ca42b070a)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	TURNSTILE_SECRET: string;
	PORTAL_ORG_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SECRET" | "PORTAL_ORG_KEY">> {}
}
