/// <reference types="astro/client" />
/// <reference types="@cloudflare/workers-types" />

/**
 * The Cloudflare Worker runtime environment.
 *
 * `Env` is generated by `pnpm cf-typegen` from wrangler.jsonc.
 * Keep worker-configuration.d.ts committed and checked in CI so bindings and
 * required secrets cannot drift away from the deploy config.
 *
 * Z360_TOKEN is intentionally optional and therefore cannot be generated from
 * Wrangler's required-secrets list. This declaration only augments the
 * generated Cloudflare environment; every required secret — TURNSTILE_SECRET
 * and PORTAL_ORG_KEY — is declared in wrangler.jsonc and generated, so it
 * must NOT be hand-written here.
 */
declare namespace Cloudflare {
  interface Env {
    /** Optional Z360 CRM token. When present (and enabled), leads are pushed to Z360. */
    Z360_TOKEN?: string;
  }
}

/**
 * BUILD-time environment variables, read through `import.meta.env` in
 * `src/config.ts`. These are a different mechanism from the Worker Secrets
 * above and must never be confused with them:
 *
 *  - `import.meta.env` is resolved by Astro when the site is BUILT and the
 *    value is baked into the bundle. Set these in `.env` locally (gitignored,
 *    see `.env.example`) and as build environment variables in the Cloudflare
 *    dashboard / CI. They are NOT `.dev.vars` entries and NOT Worker Secrets.
 *  - A real secret NEVER goes here. TURNSTILE_SECRET, PORTAL_ORG_KEY, and
 *    Z360_TOKEN stay Worker Secrets read from `cloudflare:workers`.
 *
 * Both are optional: `src/config.ts` falls back to working defaults, so a
 * fresh clone builds and runs with no `.env` at all.
 */
interface ImportMetaEnv {
  /**
   * Public Turnstile SITE key. `PUBLIC_`-prefixed because the widget renders
   * in the browser, so Astro must expose it to client code — it is not a
   * secret, and prefixing it is what makes it reachable from the island.
   */
  readonly PUBLIC_TURNSTILE_SITE_KEY?: string;
  /**
   * Origin of the portal that receives leads, e.g. a staging portal for a
   * preview build. Deliberately NOT `PUBLIC_`: only the server-side Action
   * resolves a submit URL, so this stays inlined in the Worker bundle.
   */
  readonly PORTAL_API_BASE?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
